[default]

log_level = "INFO"
log_dir = "logs"

mirrors_file = "mirrors.json"
repositories_dir = "repositories"
loop_script = false
exec_sleep = 3600

[logging]
# log_level = "DEBUG"
# log_dir = "/var/log/git-mirror"

[git]
# mirrors_file = "mirrors_other.json"
# repositories_dir = "/data/repositories"

# loop_script = true
# exec_sleep = 3600
